### ISSUE TITLE
Example please

### ISSUE THREAD

**Issue by wolframkriesing** [planetlabs/ol-maps#1]
thanks a lot for the build script. 
I am trying to get a map to render, but somehow don't get it :(
Do you have a simple example, so I can see how you use it? 
Would be awesome. Thanks a lot in advance.
I tried the following:

``` js
var ol = require('planet-maps/dist/ol-base');
var map = new ol.Map({
  layers: [
    new ol.layer.Tile({source: new ol.source.OSM()})
  ],
  view: new ol.View({
    center: ol.proj.transform([47.41, 8.82], 'EPSG:4326', 'EPSG:3857'),
    zoom: 2
  }),
  target: 'map'
});
```

yes, I added ol.source.OSM to the config and ran `make` ... no errors in the browser console :(

**Comment by wolframkriesing** [comment]
me so stupid, as usual :)
I loaded the script before the map-DOM node was available.
Thanks ... works

**Comment by tschaub** [comment]
Thanks for trying this out @wolframkriesing.  The goal here was to publish a few built profiles of the library - making it easy to include in an application without having to pull down the build tools and dependencies.  We'll likely have an "official" set of profiles published from the openlayers organization, but I thought I'd experiment with some useful ones here first.

Let me know if there are a common set of exports that you'd like to see published or if you have any other issues with this.

And, regarding the issue you encountered (trying to use a viewport target not yet in the DOM), we fail silently there (treating a bad identifier [the same as no target at all](https://github.com/openlayers/ol3/blob/84889d9dc57823f5af9f876de64cf6e8c169809f/src/ol/map.js#L945-L961)).  If you agree this is bad behavior, it would be worth [opening an issue](https://github.com/openlayers/ol3/issues/new) - we could at least throw in debug mode (we don't currently make assertions or throw in production builds).

**Comment by wolframkriesing** [comment]
thanks doing it / done
