### ISSUE TITLE
Project (npm) installs but requires to run `make`

### ISSUE THREAD

**Issue by wolframkriesing** [planetlabs/ol-maps#2]
After the `npm install` I have to go into the `node_modules/planet-maps/` and call `make`, it was not hard to find out, but I would have expected it to happen on install.
Would that make sense to include in the installation process?

**Comment by tschaub** [comment]
After `npm install`, you should see `node_modules/planet-maps/dist/ol-base.js`.  Is this not the case?

You should not need to run `make` (this is run before publishing a new release).  Instead, after `npm install`, you should be able to pull in the `ol-base.js` build in your application.  E.g.:

``` js
var ol = require('planet-maps/dist/ol-base.js');
```

This assumes you are using `browserify` to generate an application bundle.

**Comment by tschaub** [comment]
I assume you're running `npm install` from a clone of the repository.  Instead, this is meant to be installed with `npm install planet-maps` (in which case you'll get the build artifacts).  Hope this makes sense.
